baseURL = 'https://asagaoui.com/'
languageCode = 'ja'
defaultContentLanguage = "ja"
title = 'AsagaoUI'
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[languages]
[languages.ja]
languageName = "日本語"
contentDir = "content/ja"
weight = 1
[languages.ja.params]
[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 2
[languages.en.params]
