baseURL = 'https://asagaoui.com'
languageCode = 'ja'
defaultContentLanguage = "ja"
title = 'AsagaoUI'
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

[module]
proxy = "direct"
# uncomment line below for temporary local development of module
# replacements = "github.com/google/docsy -> ../../docsy"
[module.hugoVersion]
extended = true
min = "0.73.0"
[[module.imports]]
path = "github.com/google/docsy"
disable = false

[languages]
[languages.ja]
languageName = "日本語"
contentDir = "content/ja"
weight = 1
[languages.ja.params]
[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 2
[languages.en.params]
